apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-user-deployment
  labels:
    app: rpc-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rpc-user
  template:
    metadata:
      labels:
        app: rpc-user
    spec:
      imagePullSecrets:
        - name: tencentyun
      containers:
        - name: rpc-user
          image: ccr.ccs.tencentyun.com/ervinmeng/go-project:<BUILD_TAG>
          ports:
            - containerPort: 8501
          env:
            - name: branch
              value: <BRANCH_NAME>