apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-user-deployment
  labels:
    app: web-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-user
  template:
    metadata:
      labels:
        app: web-user
    spec:
      imagePullSecrets:
        - name: tencentyun
      containers:
        - name: web-user
          image: ccr.ccs.tencentyun.com/ervinmeng/go-web-user:<BUILD_TAG>
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          env:
            - name: branch
              value: <BRANCH_NAME>
---
kind: Service
apiVersion: v1
metadata:
  name: web-user-service
spec:
  selector:
    app: web-user
  ports:
    - port: 8501
      targetPort: 8501